version: "3.9"
services:
  redis:
    image: "redis:alpine"
    container_name: redis_saas
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redisDB:/data
    # networks:
    #     - db_network  #
  django_saas_postgresdb:
    restart: always
    image: postgres:latest
    container_name: django_saas_postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=DB2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    # networks:
    #    - data_network

networks:
  web_network:
    driver: bridge
volumes:
  pgdata:
  redisDB:
  appdata:
    driver: local
